// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using BaseProject.DAO.Models;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

namespace BaseProject.DAO.Data
{
    public partial class ApplicationDbContext : IdentityDbContext<AspNetUser>
    {
        public ApplicationDbContext()
        {
        }

        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Arquivo> Arquivo { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<EmpresaLogo> EmpresaLogo { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<LogAcessoUsuario> LogAcessoUsuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioFoto> UsuarioFoto { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                var configuration = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json").Build();
                optionsBuilder.UseSqlServer(configuration.GetConnectionString(Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")));
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);


            modelBuilder.Entity<EmpresaLogo>(entity =>
            {
                entity.Property(e => e.IdEmpresa).ValueGeneratedNever();

                entity.HasOne(d => d.IdEmpresaNavigation)
                    .WithOne(p => p.EmpresaLogo)
                    .HasForeignKey<EmpresaLogo>(d => d.IdEmpresa)
                    .HasConstraintName("FK_Empresa_Logo");
            });

            modelBuilder.Entity<LogAcessoUsuario>(entity =>
            {
                entity.HasOne(d => d.IdUsuarioNavigation)
                    .WithMany(p => p.LogAcessoUsuario)
                    .HasForeignKey(d => d.IdUsuario)
                    .HasConstraintName("FK_Usuario_LogAcessoUsuario");
            });

            modelBuilder.Entity<Usuario>(entity =>
            {
                entity.HasOne(d => d.IdEmpresaNavigation)
                    .WithMany(p => p.Usuario)
                    .HasForeignKey(d => d.IdEmpresa)
                    .HasConstraintName("FK_Empresa_Usuario");
            });

            modelBuilder.Entity<UsuarioFoto>(entity =>
            {
                entity.Property(e => e.IdUsuario).ValueGeneratedNever();

                entity.HasOne(d => d.IdUsuarioNavigation)
                    .WithOne(p => p.UsuarioFoto)
                    .HasForeignKey<UsuarioFoto>(d => d.IdUsuario)
                    .HasConstraintName("FK_Usuario_Foto");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}