// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BaseProject.DAO.Models
{
    [Index("CPF", Name = "IX_Usuario_CPF", IsUnique = true)]
    [Index("Email", Name = "IX_Usuario_Email", IsUnique = true)]
    [Index("IdAspNetUser", Name = "IX_Usuario_IdAspNetUser", IsUnique = true)]
    [Index("IdEmpresa", Name = "IX_Usuario_IdEmpresa")]
    public partial class Usuario
    {
        public Usuario()
        {
            LogAcessoUsuario = new HashSet<LogAcessoUsuario>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        public string IdAspNetUser { get; set; }
        public int IdEmpresa { get; set; }
        [Required]
        [StringLength(150)]
        public string Nome { get; set; }
        [Required]
        [StringLength(150)]
        public string Email { get; set; }
        [Required]
        [StringLength(11)]
        public string CPF { get; set; }
        [Required]
        public string Senha { get; set; }
        public DateTime DataCadastro { get; set; }
        public bool Ativo { get; set; }

        [ForeignKey("IdEmpresa")]
        [InverseProperty("Usuario")]
        public virtual Empresa IdEmpresaNavigation { get; set; }
        [InverseProperty("IdUsuarioNavigation")]
        public virtual UsuarioFoto UsuarioFoto { get; set; }
        [InverseProperty("IdUsuarioNavigation")]
        public virtual ICollection<LogAcessoUsuario> LogAcessoUsuario { get; set; }

        [ForeignKey("IdAspNetUser")]
        [InverseProperty("Usuario")]
        public virtual AspNetUser IdAspNetUserNavigation { get; set; }

    }
}